### ISSUE TITLE
RIMSEvalGUI v2.0.9: macOS executable broken

### ISSUE THREAD

**Issue by trappitsch** [RIMS-Code/RIMSEvalGUI#9]
**Describe the bug**
RIMSEval v2.0.9 macOS executable is damaged and doesn't even open.

**To Reproduce**
1. Download dmg from releases
2. Shift App to Applications folder
3. Open it

macOS says: "RIMSEvaluation is damaged and can't be opened. You should move it to the Trash"

**Desktop / GUI (please complete the following information):**
 - OS: macOS Big Sur
 - Version v2.0.9
 - How did you install the GUI?  Executable from release

**Comment by trappitsch** [comment]
First diagnosis suggest that this is only an issue with the executable. Not sure how many versions are affected going back, however, needs to be debugged on macOS.

Currently this has low priority, since installs via regular python and anaconda work on macOS and only the executable is reported to fail.

Regular installation: see [here](https://rimseval.readthedocs.io/en/latest/gui/install.html#anaconda)

**Comment by trappitsch** [comment]
A bit more searching, this seems to be related that the app is not signed with an official Apple ID. See, e.g., the fbs issue [here](https://github.com/mherrmann/fbs/issues/266#issuecomment-1046460445). For now, this should be included in the documentation that the user needs to strip the required argument from the app. At this point, there is no plan on incorporating full code signing via an actual Apple Developer account. 
If `fbs-pro` includes a fix for this in the future, the attribute removal will not be necessary. This should be incorporated accordingly in the docs.

**Comment by palishita** [comment]
Tried the suggested steps. It still says "Permission denied" on my computer (MacOS Big Sur 11.6.7). :(
Additionally, the anaconda version is freezing every time I attempt a mass calibration.

**Comment by palishita** [comment]
Was able to run on MacOS. 
After typing the xattr -cr /Applications/RIMSEvaluation.app in terminal, open it from the enclosing folder of the app. 

However, there's a new issue. The mass calibration window freezes on hitting apply. Happens in both, anaconda and executable, versions.

**Comment by trappitsch** [comment]
Should go into a separate issue
